# Generated by Django 5.1.1 on 2024-09-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0002_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
