# Generated by Django 5.1.1 on 2024-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('front-end', 'Front-End'), ('development', 'Development'), ('e-commerce', 'E-commerce')], max_length=50),
        ),
    ]
